# Generated by Django 5.2.8 on 2025-11-12 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('area', models.CharField(choices=[('lcc', 'Little Cottonwood Canyon'), ('o', 'ogden')], max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposedGrade', models.CharField(max_length=10)),
                ('type', models.TextField(choices=[('o', 'onsight'), ('f', 'flash'), ('r', 'redpoint')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbookApp.climb')),
            ],
        ),
    ]
