# Generated by Django 5.2.8 on 2025-11-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascent',
            name='type',
            field=models.CharField(choices=[('o', 'onsight'), ('f', 'flash'), ('r', 'redpoint')], max_length=1),
        ),
        migrations.AlterField(
            model_name='climb',
            name='area',
            field=models.CharField(choices=[('lcc', 'Little Cottonwood Canyon'), ('o', 'ogden')], default='lcc', max_length=3),
        ),
    ]
