# Generated by Django 5.2.8 on 2025-11-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbookApp', '0002_alter_ascent_type_alter_climb_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='area',
            field=models.CharField(choices=[('lcc', 'Little Cottonwood Canyon'), ('o', 'Ogden')], default='lcc', max_length=3),
        ),
    ]
