# Generated by Django 5.2.8 on 2025-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbookApp', '0003_alter_climb_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascent',
            name='date',
            field=models.DateField(),
        ),
    ]
