# Generated by Django 5.2.8 on 2025-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbookApp", "0004_alter_ascent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ascent",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
